import Link from "next/link";
import { api } from "@/lib/api";

const STEPS = [
  {
    n: "01",
    title: "Build a cohort",
    body: "Interview real respondents through a guided intake, or describe a target audience and let the model invent a cohort of distinct, specific people - same pipeline either way.",
  },
  {
    n: "02",
    title: "Agents remember",
    body: "Every answer becomes an embedded memory, scored for importance and retrievable by similarity, recency, and weight. The engine periodically synthesizes higher-level reflections from what it's seen.",
  },
  {
    n: "03",
    title: "Run a scenario",
    body: "Describe a business scenario - a price change, a new product, a repositioning - and each agent reacts in character, grounded in its own memories. Get sentiment, themes, and verbatim quotes back.",
  },
];

export default async function LandingPage() {
  const stats = await api
    .agents()
    .then((agents) => ({
      agents: agents.length,
      memories: agents.reduce((sum, a) => sum + a.observations + a.reflections, 0),
    }))
    .catch(() => null);

  return (
    <div className="min-h-screen flex flex-col">
      <header className="px-6 sm:px-10 py-6 flex items-center justify-between max-w-[1040px] w-full mx-auto">
        <div className="flex items-center gap-2">
          <div className="w-[18px] h-[18px] border-[1.5px] border-forest rounded-full flex items-center justify-center">
            <div className="w-[6px] h-[6px] bg-forest rounded-full" />
          </div>
          <span className="text-[15px] font-bold tracking-[-0.02em]">Sim0</span>
        </div>
        <Link
          href="/login"
          className="px-[16px] py-[9px] bg-forest text-paper border-none rounded-[6px] text-[13px] font-semibold no-underline hover:bg-forest-deep hover:no-underline"
        >
          Log in
        </Link>
      </header>

      <main className="flex-1 px-6 sm:px-10">
        <section className="max-w-[720px] mx-auto pt-16 pb-14 flex flex-col items-center text-center gap-6">
          <div className="px-[10px] py-[5px] rounded-full border border-rule text-[11px] tracking-[0.08em] uppercase text-[#8A8377]">
            Simulate zero data debt
          </div>
          <h1 className="text-[38px] sm:text-[46px] font-bold tracking-[-0.03em] leading-[1.08] text-ink">
            Turn interview data into agents that predict how people will actually react.
          </h1>
          <p className="text-[16px] sm:text-[17px] leading-[1.6] text-[#4A463E] max-w-[560px]">
            Sim0 builds memory-grounded LLM agents from real or synthesized interviews, then
            simulates their reactions to business scenarios at scale - so you can test a pricing
            change, a new product, or a repositioning before you ship it.
          </p>
          <div className="flex items-center gap-3 pt-2">
            <Link
              href="/login"
              className="px-[20px] py-[13px] bg-forest text-paper border-none rounded-[7px] text-[14px] font-semibold no-underline hover:bg-forest-deep hover:no-underline"
            >
              Log in to the demo
            </Link>
          </div>
          {stats && (
            <div className="flex items-center gap-6 pt-4 text-[12.5px] text-[#8A8377] tabular-nums">
              <span>{stats.agents} agents live right now</span>
              <span className="w-[3px] h-[3px] rounded-full bg-[#DCD8CE]" />
              <span>{stats.memories} memories embedded</span>
            </div>
          )}
        </section>

        <section className="max-w-[1040px] mx-auto pb-20">
          <div className="grid gap-6 sm:grid-cols-3">
            {STEPS.map((s) => (
              <div key={s.n} className="border border-rule rounded-[10px] p-6 bg-[#FCFBF8] flex flex-col gap-3">
                <span className="text-[12px] font-semibold tracking-[0.08em] text-forest">{s.n}</span>
                <span className="text-[16px] font-semibold tracking-[-0.01em]">{s.title}</span>
                <p className="m-0 text-[13.5px] leading-[1.6] text-[#6E6A60]">{s.body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="max-w-[720px] mx-auto pb-24 border-t border-rule pt-14 flex flex-col items-center text-center gap-4">
          <span className="text-[19px] font-semibold tracking-[-0.015em]">This is a live, working build</span>
          <p className="m-0 text-[13.5px] leading-[1.6] text-[#6E6A60] max-w-[480px]">
            Not a mockup - every agent, memory, and scenario response behind this login is
            generated by a real LLM pipeline against a real database. Log in to try it yourself.
          </p>
          <Link
            href="/login"
            className="px-[18px] py-[11px] border border-forest bg-transparent text-forest rounded-[6px] text-[13px] font-semibold no-underline hover:bg-forest-tint hover:no-underline"
          >
            Log in
          </Link>
        </section>
      </main>

      <footer className="px-6 sm:px-10 py-8 border-t border-rule">
        <div className="max-w-[1040px] mx-auto text-[11.5px] text-[#A8A296]">Sim0 - simulate zero data debt.</div>
      </footer>
    </div>
  );
}
